var cakeFormConstants = {
	REFRESH: 			"REFRESH",
	SET_MODEL: 			"SET_MODEL",
	
	SET_URL: 			"SET_URL",
	SET_VAL: 			"SET_VAL",
	SET_VAL_AND_UPDATE: "SET_VAL_AND_UPDATE",
	UPDATE: 			"UPDATE",

	SET_ACTIVE: 		"SET_ACTIVE",
	SET_LOCATION: 		"SET_LOCATION",

	SET_FORM_ELEMENTS: 	"SET_FORM_ELEMENTS",
	SET_DATA: 			"SET_DATA",
	SET_UNMOUNTED: 		"SET_UNMOUNTED",
	
	SAVE_DATA: 			"SAVE_DATA",

	UNSET_VAL: 			"UNSET_VAL",
	UNSET_UNMOUNTED: 	"UNSET_UNMOUNTED",
	
	LOAD_DATA: 			"LOAD_DATA",
	LOAD_DATA_URL: 		"LOAD_DATA_URL",

	ADD_DELETE_ID:  	"ADD_DELETE_ID",
	REMOVE_DELETE_ID: 	"REMOVE_DELETE_ID",

	DELETE_ID: 			"DELETE_ID"
};
export default cakeFormConstants;